package javacc.c.jtb.visitor;

import javacc.c.jtb.syntaxtree.And;
import javacc.c.jtb.syntaxtree.ArrayAssign;
import javacc.c.jtb.syntaxtree.ArrayLength;
import javacc.c.jtb.syntaxtree.ArrayLookup;
import javacc.c.jtb.syntaxtree.Assign;
import javacc.c.jtb.syntaxtree.Block;
import javacc.c.jtb.syntaxtree.BooleanType;
import javacc.c.jtb.syntaxtree.Call;
import javacc.c.jtb.syntaxtree.ClassDeclExtends;
import javacc.c.jtb.syntaxtree.ClassDeclSimple;
import javacc.c.jtb.syntaxtree.False;
import javacc.c.jtb.syntaxtree.Formal;
import javacc.c.jtb.syntaxtree.Identifier;
import javacc.c.jtb.syntaxtree.IdentifierExp;
import javacc.c.jtb.syntaxtree.IdentifierType;
import javacc.c.jtb.syntaxtree.If;
import javacc.c.jtb.syntaxtree.IntArrayType;
import javacc.c.jtb.syntaxtree.IntegerLiteral;
import javacc.c.jtb.syntaxtree.IntegerType;
import javacc.c.jtb.syntaxtree.LessThan;
import javacc.c.jtb.syntaxtree.MainClass;
import javacc.c.jtb.syntaxtree.MethodDecl;
import javacc.c.jtb.syntaxtree.Minus;
import javacc.c.jtb.syntaxtree.NewArray;
import javacc.c.jtb.syntaxtree.NewObject;
import javacc.c.jtb.syntaxtree.Not;
import javacc.c.jtb.syntaxtree.Plus;
import javacc.c.jtb.syntaxtree.Print;
import javacc.c.jtb.syntaxtree.Program;
import javacc.c.jtb.syntaxtree.This;
import javacc.c.jtb.syntaxtree.Times;
import javacc.c.jtb.syntaxtree.True;
import javacc.c.jtb.syntaxtree.Type;
import javacc.c.jtb.syntaxtree.VarDecl;
import javacc.c.jtb.syntaxtree.While;


public interface TypeVisitor {
  public Type visit(Program n);
  public Type visit(MainClass n);
  public Type visit(ClassDeclSimple n);
  public Type visit(ClassDeclExtends n);
  public Type visit(VarDecl n);
  public Type visit(MethodDecl n);
  public Type visit(Formal n);
  public Type visit(IntArrayType n);
  public Type visit(BooleanType n);
  public Type visit(IntegerType n);
  public Type visit(IdentifierType n);
  public Type visit(Block n);
  public Type visit(If n);
  public Type visit(While n);
  public Type visit(Print n);
  public Type visit(Assign n);
  public Type visit(ArrayAssign n);
  public Type visit(And n);
  public Type visit(LessThan n);
  public Type visit(Plus n);
  public Type visit(Minus n);
  public Type visit(Times n);
  public Type visit(ArrayLookup n);
  public Type visit(ArrayLength n);
  public Type visit(Call n);
  public Type visit(IntegerLiteral n);
  public Type visit(True n);
  public Type visit(False n);
  public Type visit(IdentifierExp n);
  public Type visit(This n);
  public Type visit(NewArray n);
  public Type visit(NewObject n);
  public Type visit(Not n);
  public Type visit(Identifier n);
}