package javacc.c.jtb.visitor;

import javacc.c.jtb.syntaxtree.And;
import javacc.c.jtb.syntaxtree.ArrayAssign;
import javacc.c.jtb.syntaxtree.ArrayLength;
import javacc.c.jtb.syntaxtree.ArrayLookup;
import javacc.c.jtb.syntaxtree.Assign;
import javacc.c.jtb.syntaxtree.Block;
import javacc.c.jtb.syntaxtree.BooleanType;
import javacc.c.jtb.syntaxtree.Call;
import javacc.c.jtb.syntaxtree.ClassDeclExtends;
import javacc.c.jtb.syntaxtree.ClassDeclSimple;
import javacc.c.jtb.syntaxtree.False;
import javacc.c.jtb.syntaxtree.Formal;
import javacc.c.jtb.syntaxtree.Identifier;
import javacc.c.jtb.syntaxtree.IdentifierExp;
import javacc.c.jtb.syntaxtree.IdentifierType;
import javacc.c.jtb.syntaxtree.If;
import javacc.c.jtb.syntaxtree.IntArrayType;
import javacc.c.jtb.syntaxtree.IntegerLiteral;
import javacc.c.jtb.syntaxtree.IntegerType;
import javacc.c.jtb.syntaxtree.LessThan;
import javacc.c.jtb.syntaxtree.MainClass;
import javacc.c.jtb.syntaxtree.MethodDecl;
import javacc.c.jtb.syntaxtree.Minus;
import javacc.c.jtb.syntaxtree.NewArray;
import javacc.c.jtb.syntaxtree.NewObject;
import javacc.c.jtb.syntaxtree.Not;
import javacc.c.jtb.syntaxtree.Plus;
import javacc.c.jtb.syntaxtree.Print;
import javacc.c.jtb.syntaxtree.Program;
import javacc.c.jtb.syntaxtree.This;
import javacc.c.jtb.syntaxtree.Times;
import javacc.c.jtb.syntaxtree.True;
import javacc.c.jtb.syntaxtree.VarDecl;
import javacc.c.jtb.syntaxtree.While;

public interface Visitor {
  public void visit(Program n);
  public void visit(MainClass n);
  public void visit(ClassDeclSimple n);
  public void visit(ClassDeclExtends n);
  public void visit(VarDecl n);
  public void visit(MethodDecl n);
  public void visit(Formal n);
  public void visit(IntArrayType n);
  public void visit(BooleanType n);
  public void visit(IntegerType n);
  public void visit(IdentifierType n);
  public void visit(Block n);
  public void visit(If n);
  public void visit(While n);
  public void visit(Print n);
  public void visit(Assign n);
  public void visit(ArrayAssign n);
  public void visit(And n);
  public void visit(LessThan n);
  public void visit(Plus n);
  public void visit(Minus n);
  public void visit(Times n);
  public void visit(ArrayLookup n);
  public void visit(ArrayLength n);
  public void visit(Call n);
  public void visit(IntegerLiteral n);
  public void visit(True n);
  public void visit(False n);
  public void visit(IdentifierExp n);
  public void visit(This n);
  public void visit(NewArray n);
  public void visit(NewObject n);
  public void visit(Not n);
  public void visit(Identifier n);
}