//
// Generated by JTB GJ1.1.2
//

package seven.syntaxtree;

import java.util.Enumeration;

import seven.visitor.GJNoArguVisitor;
import seven.visitor.GJVisitor;
import seven.visitor.GJVoidVisitor;
import seven.visitor.Visitor;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public interface NodeListInterface extends Node {
   public void addNode(Node n);
   public Node elementAt(int i);
   public Enumeration<Node> elements();
   public int size();

   public void accept(Visitor v);
   public <R,A> R accept(GJVisitor<R,A> v, A argu);
   public <R> R accept(GJNoArguVisitor<R> v);
   public <A> void accept(GJVoidVisitor<A> v, A argu);
}
